<a href="https://colab.research.google.com/github/ndharora2008/SVM_Classifier_in_Scikit-learn/blob/master/IRISdata_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn import datasets
from sklearn import svm
from sklearn import random_projection
import numpy as np
iris = datasets.load_iris()
digits = datasets.load_digits()

In [0]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [0]:
print(digits.target)

[0 1 2 ... 8 9 8]


In [0]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [0]:
clf = svm.SVC(gamma=0.001, C=100.)

In [0]:
clf.fit(digits.data[:-1], digits.target[:-1])  

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
rng=np.random.RandomState(0)
X=rng.rand(10,2000)
print (X)

[[0.5488135  0.71518937 0.60276338 ... 0.48010781 0.64386404 0.50177313]
 [0.81151847 0.47608399 0.52315599 ... 0.83000295 0.93280618 0.30833843]
 [0.29264205 0.56651827 0.13741443 ... 0.69652287 0.48369661 0.33955073]
 ...
 [0.32059506 0.24986687 0.03107279 ... 0.38938909 0.93272    0.33276632]
 [0.39553738 0.84401749 0.15044175 ... 0.53561083 0.35458205 0.93578099]
 [0.8140271  0.85133715 0.43113659 ... 0.44645576 0.36012661 0.62588665]]


In [0]:
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)
X_new.shape
X_new.dtype

dtype('float64')

**Iris digits dataset prediction SVM classifier Example**

In [0]:
from sklearn import datasets
from sklearn.svm import SVC
iris = datasets.load_iris()
clf=SVC(gamma='scale')
clf.fit(iris.data, iris.target)

list(clf.predict(iris.data[:3]))

clf.fit(iris.data, iris.target_names[iris.target])


list(clf.predict(iris.data[:3]))










['setosa', 'setosa', 'setosa']

In [1]:
import numpy as np
from sklearn import datasets
iris=datasets.load_iris()
iris_X=iris.data
iris_Y=iris.target
np.unique(iris_Y)


array([0, 1, 2])

**KNearestNeighbor prediction classifier for Iris dataset**

In [6]:
np.random.seed(0)
indices=np.random.permutation(len(iris_X))
iris_X_train=iris_X[indices[:-10]]
iris_Y_train=iris_Y[indices[:-10]]
iris_X_test=iris_X[indices[-10:]]
iris_Y_test=iris_Y[indices[-10:]]

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(iris_X_train,iris_Y_train)
knn.predict(iris_X_test)
iris_Y_test


array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

**Plot digits classification Exercise:**

import datasets , neighbors and linear_model

---


sklearn.datasets package - sklearn standard package

---


load_digits() - load and return the digits dataset(Hand written digits dataset)

---

load_digits(n_class=10, return_X_y=False): returns data(**dictionary like object**) : Bunch or (data, target) : tuple if return_X_y is True , dictionary like object, having attributes data to learn, images- corresponding to each target, "target_names"- the classification label for each target name.

---

calculates length of dictionary via - len(data)

---





In [10]:
print(__doc__)

from sklearn import datasets, neighbors, linear_model

digits = datasets.load_digits()
X_digits = digits.data / digits.data.max()
y_digits = digits.target

n_samples = len(X_digits)

X_train = X_digits[:int(.9 * n_samples)]
y_train = y_digits[:int(.9 * n_samples)]
X_test = X_digits[int(.9 * n_samples):]
y_test = y_digits[int(.9 * n_samples):]

knn = neighbors.KNeighborsClassifier()              
logistic = linear_model.LogisticRegression(solver='lbfgs', max_iter=1000,
                                           multi_class='multinomial')

print('KNN score: %f' % knn.fit(X_train, y_train).score(X_test, y_test))
print('LogisticRegression score: %f'
      % logistic.fit(X_train, y_train).score(X_test, y_test))




Automatically created module for IPython interactive environment
KNN score: 0.961111
LogisticRegression score: 0.933333
